# Generated by Django 5.2 on 2025-12-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'verbose_name': 'Фильм', 'verbose_name_plural': 'Фильмы'},
        ),
        migrations.RemoveField(
            model_name='movie',
            name='counries',
        ),
        migrations.AddField(
            model_name='movie',
            name='countries',
            field=models.ManyToManyField(to='movie.countries', verbose_name='В каких странах снимался этот фильм'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='actors',
            field=models.ManyToManyField(to='movie.actors', verbose_name='Актеры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='age',
            field=models.CharField(default='16+', max_length=3, verbose_name='Возрастные ограничения'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='Описание для фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='film',
            field=models.FileField(upload_to='films/', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(to='movie.genres', verbose_name='Категории для фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='posters/', verbose_name='Фотография для фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Отображение на маршруте URL'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='time',
            field=models.CharField(max_length=3, verbose_name='Длительность фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Название фильма'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='trailer',
            field=models.URLField(verbose_name='Ссылка на трейлер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.CharField(help_text='ГГГГ', max_length=4, verbose_name='Дата выхода фильма'),
        ),
        migrations.CreateModel(
            name='Serial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название сериала')),
                ('slug', models.SlugField(unique=True, verbose_name='URL для сериала')),
                ('image', models.ImageField(upload_to='serials/', verbose_name='Постер сериала')),
                ('year', models.CharField(max_length=4, verbose_name='Год выхода')),
                ('description', models.TextField(verbose_name='Описание сериала')),
                ('age', models.CharField(default='16+', max_length=3, verbose_name='Возрастное ограничение')),
                ('trailer', models.URLField(verbose_name='Ссылка на трейлер')),
                ('film', models.FileField(upload_to='serials/', verbose_name='Файл сериала')),
                ('actors', models.ManyToManyField(to='movie.actors', verbose_name='Актёры')),
                ('countries', models.ManyToManyField(to='movie.countries', verbose_name='Страны производства')),
                ('genres', models.ManyToManyField(to='movie.genres', verbose_name='Жанры сериала')),
            ],
            options={
                'verbose_name': 'Сериал',
                'verbose_name_plural': 'Сериалы',
            },
        ),
    ]
