# Generated by Django 5.2 on 2025-12-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_alter_movie_options_remove_movie_counries_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actors',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='countries',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='genres',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Отображение на маршруте URL'),
        ),
        migrations.AlterField(
            model_name='serial',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL для сериала'),
        ),
    ]
